### ISSUE TITLE
no module name einops

### ISSUE THREAD

**Issue by Tranthanhbao198** [paulpanwang/POPE#17]
Hello, i followed your tutorial, but when i run python3 visual_sam.py, i got this error: Traceback (most recent call last):
  File "/home/apicoo3569/POPE/visual_sam.py", line 1, in <module>
    from pope_model_api import *
  File "/home/apicoo3569/POPE/pope_model_api.py", line 53, in <module>
    from src.matcher import Matcher, default_cfg
  File "/home/apicoo3569/POPE/src/matcher/__init__.py", line 1, in <module>
    from .matcher import Matcher
  File "/home/apicoo3569/POPE/src/matcher/matcher.py", line 3, in <module>
    from einops.einops import rearrange
ModuleNotFoundError: No module named 'einops'

please help me to fix. thank you

**Comment by davidretinski** [comment]
Hey, you just have to install einops via pip, unfortunately the package is not in the requirements.txt

So just enter pip install einops in the terminal and it should work afterwards

**Comment by werdnabae** [comment]
Yes, this worked for me.
